version: '3.8'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: mssql
    mem_limit: 2g
    environment:
      SA_PASSWORD: "Ann@julia2010"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - opentelemetry-dotnet-first1
    volumes:
      - mssql_data:/var/opt/mssql
  otel-collector:
    restart: always
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    mem_limit: 512m
    mem_reservation: 256m
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    command:
      - '--config=/etc/otel/config.yaml'
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
      - "8889:8889" # Prometheus exporter metrics
    depends_on:
      - loki
    networks:
      - opentelemetry-dotnet-first1

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    mem_limit: 768m
    mem_reservation: 512m
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - opentelemetry-dotnet-first1
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    container_name: tempo
    mem_limit: 768m
    mem_reservation: 512m

    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    restart: always
    ports:
      - "3200:3200"  # Tempo HTTP endpoint
      - "4319:4319"  # OTLP gRPC
      - "4320:4320"  # OTLP HTTP
    networks:
      - opentelemetry-dotnet-first1    
  
  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    mem_limit: 512m
    mem_reservation: 256m     # Memória reservada (mínimo garantido)
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus  # Volume para persistência dos dados
    ports:
      - "9090:9090" 
    networks:
      - opentelemetry-dotnet-first1
  
  loki:
    restart: always
    container_name: loki
    mem_limit: 768m
    mem_reservation: 512m
    image: grafana/loki:3.5.2
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      - ./loki-data:/tmp/loki
    command:
      - '--config.file=/etc/loki/config.yaml'
    networks:
      - opentelemetry-dotnet-first1

networks:
  opentelemetry-dotnet-first1:
    driver: bridge
volumes:
  mssql_data:    
