# Receivers
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        
# Processors
processors:
  batch:

# Exporters
exporters:
  debug/traces:
    verbosity: detailed
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/tempo:
    endpoint: tempo:4319
    tls:
      insecure: true    
  prometheus:
    endpoint: "0.0.0.0:8889"
  zipkin:
        endpoint: "htp://zipkin:9411/api/v2/spans"
        tls:
          insecure: true  
# Pipelines
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      processors: [batch]
      receivers: [otlp]
      exporters: [otlp/jaeger, otlp/tempo,debug/traces]
    logs:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [otlphttp/logs]